
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_employer_development

test:
  <<: *default
  database: db_employer_test

production:
  <<: *default
  database: db_employer_production

